version: "3.9"

services:
  paternity-backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend-paternity:/app
    environment:
      - DEBUG=true

  paternity-frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: react-frontend
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - paternity-backend
      - paternity-frontend
